# Generated by Django 5.2.15 on 2026-06-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(default='default', max_length=50)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for auto-categorization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
